# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hocus_pocus}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Akira Matsuda"]
  s.date = %q{2010-12-22}
  s.description = %q{An Isolated Engine that casts a spell on your Rails 3.1 app}
  s.email = %q{ronnie@dio.jp}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/hocus_pocus/application_controller.rb",
    "app/controllers/hocus_pocus/editor_controller.rb",
    "app/controllers/hocus_pocus/generator_controller.rb",
    "app/helpers/hocus_pocus/application_helper.rb",
    "app/helpers/hocus_pocus/generator_helper.rb",
    "app/views/hocus_pocus/editor/_editor.html.erb",
    "app/views/hocus_pocus/editor/index.js.erb",
    "app/views/hocus_pocus/editor/save.js.erb",
    "app/views/hocus_pocus/generator/execute.js.erb",
    "app/views/hocus_pocus/generator/index.html.erb",
    "app/views/hocus_pocus/generator/scaffold.js.erb",
    "config/routes.rb",
    "hocus_pocus.gemspec",
    "lib/hocus_pocus.rb",
    "lib/hocus_pocus/engine.rb",
    "lib/hocus_pocus/filter.rb",
    "lib/tasks/hocus_pocus_tasks.rake",
    "public/javascripts/rails.js",
    "test/helper.rb",
    "test/test_hocus_pocus.rb"
  ]
  s.homepage = %q{http://github.com/amatsuda/hocus_pocus}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An Isolated Engine that casts a spell on your Rails 3.1 app}
  s.test_files = [
    "test/helper.rb",
    "test/test_hocus_pocus.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<nested_scaffold>, [">= 0.1.0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<nested_scaffold>, [">= 0.1.0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<nested_scaffold>, [">= 0.1.0"])
  end
end

